[project]
name = "prompt-playground"
version = "1.0.0"
description = "Test your prompts with various models and configurations"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "semantic-kernel>=1.32.2",
    "streamlit>=1.45.1",
]
